default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost  # ajouté
  variables:       # ajouté
    timezone: 'Europe/Paris'  # ajouté

development:
  <<: *default
  database: dispr_development

test:
  <<: *default
  database: dispr_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>