default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: puramontero
  password: password
  host: localhost  # ajouté
  variables:       # ajouté
    timezone: 'Europe/Paris'  # ajouté

development:
  <<: *default
  database: puramontero   

test:
  <<: *default
  database: dpuramontero

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>